### ISSUE TITLE
enhancement : docker

### ISSUE THREAD

**Issue by hugokoopmans** [PetervanLunteren/EcoAssist#20]
great work, would this be easely deployable in a docker container?

**Comment by PetervanLunteren** [comment]
hi @hugokoopmans,

I've never really worked with docker before, so I don't really know... It would definitely be nice to be able to prevent installation/platform-based limitations. What would be the criteria for a docker container?

**Comment by ehallein** [comment]
No reason you couldn't run it through docker using Ubuntu or similar by installing it normally. But you would need to install a desktop linux environment and VNC into it (remember EcoAssist is a GUI application) and configure docker to access the GPU if you want acceleration.

**Comment by gimmw** [comment]
I've been testing EcoAssist _sucessfully_ in a container (Apptainer in my case, but Docker should work similarly with some extra work to get a GUI working).

See Dockerfile here: https://gist.github.com/gimmw/015bced25d6a25ca0b0d743de689bf5d
The resulting docker image was then converted into an apptainer image, and run with
    
    apptainer --nv --writable-tmpfs --mount type=bind,source=$HOME/.ecoassist,destination=/rw ecoassist.sif

As you might note, most of what's happening in the Dockerfile are workarounds for the fact that EA expects ownership/write access to the whole installation, whereas in a container you want to keep as much as possible read-only and have any persistent storage living outside of the container.

`--writable-tmpfs` in apptainer adds a non-persist writable overlay, as an easy workaround for the git co in switch_model wanting to create a git lockfile and fatally crashing when it can't.

There are also button/widget rendering artefacts, but I believe that's a known issue with tkinter.

Seems to work alright for the rest.


What would help immensely to make this much more easily containerizable:
- assuming the user running the application may not be the owner of the EA install
- assuming we may not want any automatic updates at runtime
- the clear separation of writable directories and files (config files, log files, downloadable models) in configurable or arbitrary user-specific path (eg ~/.ecoassist) rather than having everything in a single non-configurable prefix

**Comment by PetervanLunteren** [comment]
@gimmw Great job!

@hugokoopmans, would this be something that you can work with?
