### ISSUE TITLE
How to change install drive - Install EcoAssist on a custom location

### ISSUE THREAD

**Issue by jillwettlaufer** [PetervanLunteren/EcoAssist#22]
Is it possible to change the drive it's installed on if I'm installing without admin privledges? It wants to install on my M drive but that only has 1 GB of storage so I'd prefer to change it to my C drive.

|--------------------------- ECOASSIST INSTALLATION ---------------------------|

It seems like you don't have admin rights. Do you want to proceed to install for all users and enter an admin password, or install EcoAssist only for you (no admin rights required)?
Enter [O]nly me or [P]roceed as admin: O

Proceeding to install in userfolder...

Proceeding to install...
Install script is located on drive:    'C:'
EcoAssist will be installed on drive:  'M:'
Changed drive to:                      'M:'
Prefix:                                'M:'
Location:                              'M:\EcoAssist_files'
Created empty dir:                     'M:\EcoAssist_files'

**Comment by PetervanLunteren** [comment]
Yes, it is possible to install it at a custom location. There is a built-in option to choose a custom location, but the user is only prompted with this if their homefolder is not accessible. Since your homefolder is accessible, (but just not preferred), we can trick the script in to thinking that your homefolder is not accessible.

1. Open your install.bat file with a text editor like NotePad or Visual Studio Code;
2. Find [this line](https://github.com/PetervanLunteren/EcoAssist/blob/main/install.bat#L35) and add some random text to the path. For example: `"%homedrive%%homepath%\blahblahblah\"` Make sure you leave the indenting and the rest as it was.
3. Save, close and execute the file again.

If you choose to install EcoAssist [O]nly for your user, you should get the option to choose a custom location. You can enter for example `C:\some\desired\path\`.
