### ISSUE TITLE
finding pictures with unknown animals

### ISSUE THREAD

**Issue by TinaH10** [PetervanLunteren/EcoAssist#46]
Hello,

we have deployed camera traps at bird nests, to monitor nest predation as part of a scientific project. We do currently NOT know which animals will predate the nest (if any). Is it possible to use EcoAssist to detect any unknown animal? Or does it need to be trained to detect certain known animal species? 

Ideally, we would like to do both, capture all pictures were the resident birds visit the nest (a small songbird), and secondly, monitor for possible unknown predators. 

Thanks for your help how this can be best achieved.

**Comment by PetervanLunteren** [comment]
Hi @TinaH10,

It's good to know that species identification models are always developed for a specific project and ecosystem. Sometimes a model can be useful for other projects too, but that is dependent on how comparable the ecosystem, camera setup, resolution, etc, is. Models should always be thoroughly tested before accepting the results.

In your case, I don't know where in the world your project is and if any of the available models would be applicable (Namibia, New Zealand, Amazon, or Europe). Birds generally are quite similar in different ecosystems (most of them have a bill, feathers and wings), so that might be beneficial for you. I'd say - just try out some different models and see what works best for you. 

You can also choose to not identify the animals, and only use MegaDetector. That will give you "animal" or "empty", which is already a great help. 

If you decide to develop your own model, keep in mind that you'll need training data of the actual setup. With all the animals present and annotated.

**Comment by TinaH10** [comment]
Thank you. I have since learned a lot more about this and am quite happy with the "animal" classification :-)!

**Comment by PetervanLunteren** [comment]
Glad to hear that :) let me know if you ned more assistance
