### ISSUE TITLE
Several problems

### ISSUE THREAD

**Issue by Niemand112233** [PetervanLunteren/EcoAssist#53]
Hi,

I installed EcoAssist, but it installed itself on a network drive?! Why can't I choose where it should install? I don't want it to be installed on a network drive...

Second, I get this error: "Error An error has occured: charmap codec can't decode byte 0x81 in position 59: character maps to <undefined>.

What is the problem? 

 I'm running Win11

**Comment by PetervanLunteren** [comment]
I've automated the install so that it gets easy for users without CLI experience. You can adjust the install location in the install script https://github.com/PetervanLunteren/EcoAssist/blob/main/install.bat.

If you keep having the same problem, please copy-paste the entire console output from the installation and send it to me at peter@addaxdatascience.com.
